---
- name: Testing andrewrothstein.kn
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kn version'
      ansible.builtin.command: /usr/local/bin/kn version
      changed_when: false
      register: kn_test_output
    - name: Output from 'kn version'
      ansible.builtin.debug:
        msg: '{{ kn_test_output.stdout }}'
