---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kn version
    register: kn_test_output
  - name: kn version
    debug:
      msg: '{{ kn_test_output.stdout }}'
